name: Update Story Data

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl unzip

      - name: Get Version Name
        id: version
        run: |
          API_URL="https://webapi.lowiro.com/webapi/serve/static/bin/arcaea/apk/"
          VERSION=$(curl -fsSL "$API_URL" | jq -er 'select(.success == true) | .value.version')
          echo "name=${VERSION%c}" >> "$GITHUB_OUTPUT"

      - name: Run Update Script
        run: bash update.sh

      - name: Commit
        uses: EndBug/add-and-commit@v10
        with:
          default_author: github_actions
          message: "${{ steps.version.outputs.name }}"
